name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositori
        uses: actions/checkout@v4

      - name: Instal·la Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instal·la les dependències
        run: pip install -r requirements.txt

      - name: Executa les migracions
        run: python manage.py migrate
        env:
          DJANGO_SETTINGS_MODULE: my_site.settings

      - name: Executa pydoc
        run: python -c "import django; django.setup(); import pydoc; pydoc.writedoc('blog.views')"
        env:
          DJANGO_SETTINGS_MODULE: my_site.settings
